# Generated by Django 5.2 on 2025-05-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_board'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
