# Generated by Django 5.2 on 2025-05-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_delete_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text="The user's unique email address (used for login).", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(help_text="The user's full name (e.g. John Doe).", max_length=150),
        ),
    ]
